config/routes.rb
Rails.application.routes.draw do

  resources :statuses

  resources :countries

  resources :pages

  root 'statuses#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'about' => 'static_pages#about'
  get 'terms' => 'static_pages#terms'
  get 'contact' => 'static_pages#contact'
  
  controller :sessions do
    post 'login' => :create
    delete 'logout' => :destroy
  end

  namespace :laapi do
    resources :statuses, only: [ :index, :show ]
    post 'statuses' => 'statuses#index'

    resources :requests, only: [ :create, :show ]
  end

end

app/views/pages/_form.html.erb
<%= simple_form_for(@page, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.input :url %>
  <%= f.input :title %>
  <%= f.association :categories, as: :check_boxes %>
  <%= f.button :submit %>
  <%= link_to :back do %>
    <button type="button" class="btn btn-default">
      Cancel
    </button>
  <% end %>
<% end %>

app/views/pages/_group_link.html.erb
<%= link_to render( partial: 'pages/icon_title', object: group_link ), group_link, class: 'list-group-item', title: group_link.url %>

app/views/pages/_icon_title.html.erb
<%= favicon_tag(icon_title.id) %> <span><%= title_or_url icon_title %></span>

app/views/pages/_page.html.erb
<div class="page media">
  <div class="favicon-container">
    <%= link_to favicon_tag(page.id, class: 'media-object'), page_path(page) %>
  </div>

  <div class="media-body">
    <h4 class="media-heading"><%= page.title %></h4>

    <% if page.url.length > 60 %>
      <p class="truncated-url"><%= truncate(page.url, length: 80) %></p>
      <p class="full-url"><%= page.url %></p>
    <% else %>
      <p class="url"><%= page.url %></p>
    <% end %>

    <p>
      <%= page.category_names.join(', ') %>
    </p>
  </div>
</div>

app/views/pages/_recent_statuses.html.erb
<% @statuses.each do |status_group| %>
  <div class="list-group pages-status-<%= status_context_class status_group[1][0] %>">
    <div class="list-group-item list-group-item-<%= status_context_class status_group[1][0] %>">
      <%= t "statuses.#{status_group[0]}" %>
    </div>

    <% status_group[1].each do |status| %>
      <%= link_to status.country.name, status, class: 'list-group-item' %>
    <% end %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Edit Page</h1>

<%= render 'form' %>

app/views/pages/index.html.erb
<h1><%= t 'models.pages' %></h1>

<%= link_to new_page_path do %>
  <button id="new-page" type="button" class="btn btn-default">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Page
  </button>
<% end %>

<div class="btn-group pull-right">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <% if params[:category].present? %>
      Category: <%= params[:category] %>
    <% else %>
      Filter by Category
    <% end %>

    <span class="caret"></span>
  </button>

  <ul class="dropdown-menu">
    <% @categories.each do |category| %>
      <li>
        <a href="?category=<%= category.name %>"><%= category.name %></a>
      </li>
    <% end %>
  </ul>
</div>

<p class="pages-help alert alert-info"><%= t 'pages.help' %></p>

<div class="list-group pages-list">
  <%= render partial: 'pages/group_link', collection: @pages %>
</div>

app/views/pages/new.html.erb
<h1>Pages#add</h1>
<p>Find me in app/views/pages/add.html.erb</p>

app/views/pages/show.html.erb
<% cache_if(@cache_key.present?, "pages/#{@page.id}/#{@cache_key}", expires_in: cache_duration) do %>
  <%= render @page %>

  <%= link_to edit_page_path(@page) do %>
    <button type="button" class="btn btn-primary">
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
    </button>
  <% end %>

  <%= button_to @page, method: :delete, data: { confirm: 'Are you sure you want to delete this page?' }, form_class: 'delete', class: 'btn btn-danger' do %>
    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete
  <% end %>

  <h2><%= t 'pages.recent' %></h2>

  <% if @statuses.any? %>
    <%= render 'recent_statuses' %>
  <% else %>
    <p>No recent statuses.</p>
  <% end %>
<% end %>