config/routes.rb
Rails.application.routes.draw do

  resources :statuses

  resources :countries

  resources :pages

  root 'statuses#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'about' => 'static_pages#about'
  get 'terms' => 'static_pages#terms'
  get 'contact' => 'static_pages#contact'
  
  controller :sessions do
    post 'login' => :create
    delete 'logout' => :destroy
  end

  namespace :laapi do
    resources :statuses, only: [ :index, :show ]
    post 'statuses' => 'statuses#index'

    resources :requests, only: [ :create, :show ]
  end

end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :proxies
  has_many :statuses

  scope :having_requests_on, -> ( date ) {
    where( %Q|id IN ( SELECT DISTINCT "country_id" FROM "requests" WHERE ( CAST( "created_at" AS DATE ) = '#{date.to_s}' ) )| )
  }
  scope :has_statuses, ->{ where("id IN (#{Status.select(:country_id).distinct.to_sql})") }
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: :show

  def index
    @cache_key = Status.order(created_at: :desc).first.try(:created_at).try(:to_i)
    @countries = Country.has_statuses
  end

  def show
    @cache_key = @country.statuses.order(created_at: :desc).first.try(:created_at).try(:to_i)
    @statuses = @country.statuses.includes(:page).select(
      'distinct on (page_id) *'
    ).order(
      page_id: :asc, created_at: :desc
    ).group_by(&:value).sort_by { |sg| sg[0] }
  end

  private

  def set_country
    @country = Country.find(params[:id])
  end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_country.html.erb
<div class="country media">
  <%= link_to image_tag( "flags/#{country.iso2}.png", class: 'media-object' ), country_path( country ), class: 'pull-left' %>
  <div class="media-body">
    <h4 class="media-heading"><%= country.name %></h4>
    <div class="statusBarContainer" data-statuses="<%= NewestStatusFinder.status_bar_data(country, NewestStatusFinder.per_page_for_country(country)).to_json %>">
    </div>
  </div>
</div>

app/views/countries/index.html.erb
<% cache_if(@cache_key.present?, "countries/index/#{@cache_key}", expires_in: cache_duration) do %>
  <h1>Countries</h1>

  <ul class="countries-list">
    <%= render partial: 'shared/list_item', collection: @countries %>
  </ul>
<% end %>

app/views/countries/show.html.erb
<% cache_if(@cache_key.present?, "countries/#{@country.id}/#{@cache_key}", expires_in: cache_duration) do %>
  <%= render @country %>

  <h2><%#= t 'countries.changed_since' %></h2>

  <h2><%= t 'countries.recent' %></h2>

  <div id="accordion">
    <% @statuses.each do |status_group| %>
      <div class="list-group pages-status-<%= status_context_class status_group[1][0] %>">
        <%= link_to(
          "##{status_context_class(status_group[1][0])}",
          class: "list-group-item list-group-item-#{status_context_class status_group[1][0]}",
          data: { toggle: 'collapse', parent: '#accordion' }
        ) do %>
          <%= t("statuses.#{status_group[0]}") %>
          <span class="badge"><%= status_group[1].size %></span>
        <% end %>

        <%= content_tag :div, id: status_context_class(status_group[1][0]), class: "panel-collapse collapse" do %>
          <% status_group[1].each do |status| %>
            <%= link_to title_or_url( status.page ), status, class: 'list-group-item' %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>