config/routes.rb
Rails.application.routes.draw do

  resources :statuses

  resources :countries

  resources :pages

  root 'statuses#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'about' => 'static_pages#about'
  get 'terms' => 'static_pages#terms'
  get 'contact' => 'static_pages#contact'
  
  controller :sessions do
    post 'login' => :create
    delete 'logout' => :destroy
  end

  namespace :laapi do
    resources :statuses, only: [ :index, :show ]
    post 'statuses' => 'statuses#index'

    resources :requests, only: [ :create, :show ]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>

    <title><%= t 'app_name' %></title>

    <link href='http://fonts.googleapis.com/css?family=Lora:700' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag    'application', media: 'all' %>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body class="<%= "#{params[ :controller ]} #{params[ :action ]}" %>">
    <header>
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
          <%= link_to 'NetClerk', statuses_path, class: 'navbar-brand' %>
          </div>
          <div id="navbar">
            <ul class="nav navbar-nav">
              <li <%= 'class="active"'.html_safe if controller.controller_name == 'statuses' %>>
                <%= link_to t( 'statuses.recent' ), statuses_path %>
              </li>
              <li <%= 'class="active"'.html_safe if controller.controller_name == 'pages' %>>
                <%= link_to t( 'models.pages' ), pages_path %>
              </li>
              <li <%= 'class="active"'.html_safe if controller.controller_name == 'countries' %>>
                <%= link_to t( 'models.countries' ), countries_path %>
              </li>
              <li <%= 'class="active"'.html_safe if current_page?(about_path) %>>
                <%= link_to t('static_pages.about.title'), about_path %>
              </li>
              <li <%= 'class="active"'.html_safe if current_page?(terms_path) %>>
                <%= link_to t('static_pages.terms.title'), terms_path %>
              </li>
              <li <%= 'class="active"'.html_safe if current_page?(contact_path) %>>
                <%= link_to t('static_pages.contact.title'), contact_path %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="container">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>

    <!-- Setup BrowserID with alert debugging -->
    <%= setup_browserid debug: Rails.const_defined?( 'Server' ) %>
  </body>
</html>